name: "(TG) Choose your pipeline"

on:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
        default: "Release"
      extra-tag:
        required: true
        type: string
        default: "in-service"
      build-with-tracy:
        required: false
        type: boolean
        default: false
      tg-quick:
        required: false
        type: boolean
        default: false
      tg-demo:
        required: false
        type: boolean
        default: false
      tg-unit:
        required: false
        type: boolean
        default: false
      tg-frequent:
        required: false
        type: boolean
        default: false
      tg-model-perf:
        description: "TG model perf tests (requires tracy build)"
        required: false
        type: boolean
        default: false
      tg-nightly:
        required: false
        type: boolean
        default: false

run-name: ${{ inputs.description }}
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-type: ${{ inputs.build-type }}
      tracy: ${{ inputs.build-with-tracy }}
      build-wheel: true
      version: 22.04
  tg-quick:
    if: ${{ inputs.tg-quick }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-quick.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-unit-tests:
    if: ${{ inputs.tg-unit }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-unit-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-frequent-tests:
    if: ${{ inputs.tg-frequent }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-frequent-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-demo-tests:
    if: ${{ inputs.tg-demo }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-demo-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-model-perf-tests:
    if: ${{ inputs.tg-model-perf }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-model-perf-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-nightly-tests:
    needs: build-artifact
    if: ${{ inputs.tg-nightly }}
    secrets: inherit
    uses: ./.github/workflows/tg-nightly-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
